version: "2"
run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - bodyclose
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gosec
    - ineffassign
    - revive
    - unused

  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: github.com/blagovibe/TorrSyncPlayer

  exclusions:
    rules:
      - linters: [revive]
        text: "unused-parameter"
      - linters: [revive]
        text: "exported"
      - linters: [revive]
        text: "package-comments"
      - linters: [revive]
        text: "empty-block"
