version: "2"
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - bodyclose
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gosec
    - ineffassign
    - revive
    - unused
  disable: []

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/blagovibe/TorrSyncPlayer

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters: [revive]
      text: "unused-parameter"
    - linters: [revive]
      text: "exported"
    - linters: [revive]
      text: "package-comments"
    - linters: [revive]
      text: "empty-block"
