// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 TorrSyncPlayer contributors
// See LICENSE file for full license text

// Package main server entry point.
package main

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"flag"
	"fmt"
	"math/big"
	"net"
	"net/http"
	"net/http/pprof"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	"github.com/blagovibe/TorrSyncPlayer/backend/internal/api"
	"github.com/blagovibe/TorrSyncPlayer/backend/internal/auth"
	"github.com/blagovibe/TorrSyncPlayer/backend/internal/buffer"
	"github.com/blagovibe/TorrSyncPlayer/backend/internal/constants"
	"github.com/blagovibe/TorrSyncPlayer/backend/internal/p2p"
	"github.com/blagovibe/TorrSyncPlayer/backend/internal/sync"
	"github.com/blagovibe/TorrSyncPlayer/backend/internal/torrent"
	"github.com/blagovibe/TorrSyncPlayer/backend/internal/version"
	"github.com/blagovibe/TorrSyncPlayer/backend/pkg/logger"
)

// @title           TorrSyncPlayer API
// @version         1.0
// @description     HTTP API for TorrSyncPlayer — torrent player with P2P playback synchronization.
// @termsOfService  https://github.com/blagovibe/TorrSyncPlayer

// @contact.name   TorrSyncPlayer Support
// @contact.url    https://github.com/blagovibe/TorrSyncPlayer/issues
// @contact.email  support@torrsyncplayer.local

// @license.name  MIT
// @license.url   https://opensource.org/licenses/MIT

// @host      localhost:8889
// @BasePath  /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Enter JWT token in the format: Bearer <token>

const (
	defaultPort     = "8889"
	defaultDir      = "./data"
	shutdownTimeout = 30 * time.Second
)

// Config server configuration
type Config struct {
	Port                  string
	DataDir               string // Directory for persistent data (empty = in-memory)
	MemoryStorageCapacity int64  // Maximum in-memory storage size in bytes
	TLSCert               string
	TLSKey                string
	UseTLS                bool
	AutoTLS               bool // Generate self-signed certificate
	autoGenerated         bool // Certificate was auto-generated, not user-provided
	JWTSecret             string
	EnableProfiling       bool // Enable pprof profiling
}

func main() {
	config := parseFlags()

	logLevel := getEnv("LOG_LEVEL", "info")
	logFormat := getEnv("LOG_FORMAT", "text")
	logger.Init(logLevel, logFormat)

	if err := validateConfig(config); err != nil {
		logger.Error("Configuration error", "error", err)
		os.Exit(1)
	}

	logger.Info("Starting TorrServer",
		"version", version.Version,
		"commit", version.Commit,
		"build_time", version.BuildTime,
	)

	// Create auth service
	authService, err := auth.NewAuthService([]byte(config.JWTSecret))
	if err != nil {
		logger.Error("Failed to create auth service", "error", err)
		os.Exit(1)
	}

	// Initialize buffer service
	bufferSvc := buffer.NewService(constants.DefaultMaxBufferSize)
	bufferSvc.StartPeriodicUpdate(constants.BufferUpdateInterval)

	// Torrent service options (always in-memory)
	torrentOpts := torrent.ServiceOptions{
		MemoryStorageCapacity: config.MemoryStorageCapacity,
	}

	// Initialize torrent service with buffer and in-memory storage
	torrentSvc, err := torrent.NewServiceWithOptions(bufferSvc, torrentOpts)
	if err != nil {
		logger.Error("Failed to initialize torrent service", "error", err)
		os.Exit(1)
	}

	logger.Info("Torrent service initialized",
		"memory_capacity", config.MemoryStorageCapacity,
	)

	p2pSvc, err := p2p.NewService(authService)
	if err != nil {
		logger.Error("Failed to initialize P2P service", "error", err)
		os.Exit(1)
	}

	syncSvc := sync.NewService()

	// Create user store
	authStore := auth.NewUserStore()
	if config.DataDir != "" {
		if err := authStore.SetPersistence(config.DataDir); err != nil {
			logger.Error("Failed to initialize persistence for UserStore", "error", err)
		}
		if err := authService.SetPersistence(config.DataDir); err != nil {
			logger.Error("Failed to initialize persistence for TokenRevocationStore", "error", err)
		}
	}

	// Create router
	router := api.NewRouter(api.RouterConfig{
		TorrentSvc:  torrentSvc,
		P2pSvc:      p2pSvc,
		SyncSvc:     syncSvc,
		AuthStore:   authStore,
		AuthService: authService,
	})

	// Configure HTTP server
	server := &http.Server{
		Addr:         fmt.Sprintf(":%s", config.Port),
		Handler:      router,
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  120 * time.Second,
	}

	if config.UseTLS {
		tlsConfig, err := configureTLS(&config)
		if err != nil {
			logger.Error("Failed to configure TLS", "error", err)
			os.Exit(1)
		}
		server.TLSConfig = tlsConfig
		defer func() {
			if config.autoGenerated {
				if config.TLSCert != "" {
					logger.Debug("Cleaning up auto-generated TLS cert", "path", config.TLSCert)
					_ = os.Remove(config.TLSCert)
				}
				if config.TLSKey != "" {
					logger.Debug("Cleaning up auto-generated TLS key", "path", config.TLSKey)
					_ = os.Remove(config.TLSKey)
				}
			} else if config.TLSCert != "" {
				logger.Debug("User-provided TLS cert — not removing", "cert", config.TLSCert, "key", config.TLSKey)
			}
		}()
	}

	// Setup pprof if enabled
	var pprofServer *http.Server
	if config.EnableProfiling {
		pprofServer = setupPprof()
		logger.Info("pprof profiling enabled", "endpoint", "/debug/pprof/")
	}

	// Start server in goroutine
	go func() {
		defer func() {
			if r := recover(); r != nil {
				logger.Error("HTTP server: goroutine exited with panic", "error", r)
			}
		}()
		logger.Info("HTTP server started", "port", config.Port, "tls", config.UseTLS)
		var err error
		if config.UseTLS {
			err = server.ListenAndServeTLS(config.TLSCert, config.TLSKey)
		} else {
			err = server.ListenAndServe()
		}
		if err != nil && err != http.ErrServerClosed {
			logger.Error("HTTP server error", "error", err)
			os.Exit(1)
		}
	}()

	// Wait for shutdown signal
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	sig := <-quit
	logger.Info("Received shutdown signal", "signal", sig.String())

	// Graceful shutdown
	ctx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
	defer cancel()

	// Stop HTTP server
	if err := server.Shutdown(ctx); err != nil {
		logger.Error("Error stopping HTTP server", "error", err)
	}
	logger.Info("HTTP server stopped")

	// Stop sync service
	syncSvc.Close()

	// Stop P2P service
	if err := p2pSvc.Close(); err != nil {
		logger.Error("Error stopping P2P service", "error", err)
	}

	// Stop torrent service
	if err := torrentSvc.Close(); err != nil {
		logger.Error("Error stopping torrent service", "error", err)
	}

	// Stop buffer service
	bufferSvc.Close()

	// Stop rate limiter cleanup goroutines
	api.StopGlobalRateLimiters()

	// Stop auth service (including revocation store cleanup)
	authService.Stop()

	// Stop CSRF cleanup goroutine
	api.CSRFStore.Stop()

	// Stop pprof server gracefully
	if pprofServer != nil {
		pprofCtx, pprofCancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer pprofCancel()
		if err := pprofServer.Shutdown(pprofCtx); err != nil {
			logger.Error("Error stopping pprof server", "error", err)
		}
		logger.Info("pprof server stopped")
	}

	logger.Info("Server stopped")
}

// validateConfig validates the server configuration.
// Returns an error if the configuration is invalid.
func validateConfig(config Config) error {
	if config.JWTSecret == "" {
		return fmt.Errorf("JWT secret is required — set via JWT_SECRET environment variable (minimum 32 bytes)")
	}
	if len(config.JWTSecret) < 32 {
		return fmt.Errorf("JWT secret too short: got %d bytes, minimum 32", len(config.JWTSecret))
	}

	port, err := strconv.Atoi(config.Port)
	if err != nil || port < 1 || port > 65535 {
		return fmt.Errorf("invalid port: %s (must be 1-65535)", config.Port)
	}

	if config.MemoryStorageCapacity < 0 {
		return fmt.Errorf("memory-capacity cannot be negative: %d", config.MemoryStorageCapacity)
	}
	if config.MemoryStorageCapacity > constants.MaxMemoryStorageCapacity {
		return fmt.Errorf("memory-capacity exceeds maximum: %d > %d", config.MemoryStorageCapacity, constants.MaxMemoryStorageCapacity)
	}

	if !config.UseTLS {
		logger.Warn("Running without TLS — all data is transmitted in plain text. Do not use in production!")
	}

	return nil
}

// parseFlags parses command-line flags
func parseFlags() Config {
	var config Config

	flag.StringVar(&config.Port, "port", getEnv("PORT", defaultPort), "Server port")
	flag.StringVar(&config.DataDir, "data-dir", getEnv("DATA_DIR", ""), "Directory for persistent data (empty = in-memory only)")
	flag.Int64Var(&config.MemoryStorageCapacity, "memory-capacity", func() int64 {
		if v := os.Getenv("MEMORY_CAPACITY"); v != "" {
			if n, err := strconv.ParseInt(v, 10, 64); err == nil {
				return n
			}
		}
		return constants.DefaultMemoryStorageCapacity
	}(), "Maximum in-memory storage size in bytes (0 = unlimited)")
	flag.StringVar(&config.TLSCert, "tls-cert", getEnv("TLS_CERT", ""), "Path to TLS certificate")
	flag.StringVar(&config.TLSKey, "tls-key", getEnv("TLS_KEY", ""), "Path to TLS key")
	flag.BoolVar(&config.UseTLS, "tls", false, "Enable TLS")
	flag.BoolVar(&config.AutoTLS, "auto-tls", false, "Generate self-signed certificate")
	flag.BoolVar(&config.EnableProfiling, "enable-profiling", false, "Enable pprof profiling")

	flag.Parse()

	config.JWTSecret = getEnv("JWT_SECRET", "")
	if config.JWTSecret == "" {
		logger.Error("JWT_SECRET environment variable is not set. Set it to a secure random string of at least 32 characters.")
		os.Exit(1)
	}

	if config.AutoTLS {
		config.UseTLS = true
		if config.TLSCert == "" || config.TLSKey == "" {
			cert, key, err := generateSelfSignedCert()
			if err != nil {
				logger.Error("Failed to generate self-signed certificate", "error", err)
				os.Exit(1)
			}
			config.TLSCert = cert
			config.TLSKey = key
			config.autoGenerated = true
		}
	}

	// If certificates are specified, enable TLS
	if config.TLSCert != "" && config.TLSKey != "" {
		config.UseTLS = true
	}

	return config
}

// configureTLS configures TLS settings
func configureTLS(config *Config) (_ *tls.Config, retErr error) {
	var cleanup func()
	if config.TLSCert == "" || config.TLSKey == "" {
		logger.Warn("TLS certificates not specified, generating self-signed certificate")
		cert, key, err := generateSelfSignedCert()
		if err != nil {
			return nil, fmt.Errorf("certificate generation error: %w", err)
		}
		config.TLSCert = cert
		config.TLSKey = key
		config.autoGenerated = true

		cleanup = func() {
			_ = os.Remove(config.TLSCert)
			_ = os.Remove(config.TLSKey)
		}
	}

	cert, err := tls.LoadX509KeyPair(config.TLSCert, config.TLSKey)
	if err != nil {
		if cleanup != nil {
			cleanup()
		}
		config.TLSCert = ""
		config.TLSKey = ""
		return nil, fmt.Errorf("certificate loading error: %w", err)
	}

	return &tls.Config{
		Certificates: []tls.Certificate{cert},
		MinVersion:   tls.VersionTLS12,
		CipherSuites: []uint16{
			tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
			tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
			tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
			tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
		},
	}, nil
}

// generateSelfSignedCert generates a self-signed certificate for development
func generateSelfSignedCert() (certPath, keyPath string, err error) {
	// Generate private key
	privateKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return "", "", fmt.Errorf("key generation error: %w", err)
	}

	serialNumber, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return "", "", fmt.Errorf("serial number generation error: %w", err)
	}

	// Create certificate template
	template := x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			Organization: []string{"TorrSyncPlayer"},
			CommonName:   "localhost",
		},
		NotBefore:             time.Now(),
		NotAfter:              time.Now().Add(365 * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		IPAddresses:           []net.IP{net.ParseIP("127.0.0.1"), net.ParseIP("::1")},
		DNSNames:              []string{"localhost"},
	}

	// Generate certificate
	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, &privateKey.PublicKey, privateKey)
	if err != nil {
		return "", "", fmt.Errorf("certificate creation error: %w", err)
	}

	certFile, err := os.CreateTemp("", "cert-*.pem")
	if err != nil {
		return "", "", fmt.Errorf("certificate file creation error: %w", err)
	}
	if err := os.Chmod(certFile.Name(), 0600); err != nil {
		certFile.Close()
		os.Remove(certFile.Name())
		return "", "", fmt.Errorf("failed to set certificate file permissions: %w", err)
	}

	keyFile, err := os.CreateTemp("", "key-*.pem")
	if err != nil {
		certFile.Close()
		os.Remove(certFile.Name())
		return "", "", fmt.Errorf("key file creation error: %w", err)
	}
	if err := os.Chmod(keyFile.Name(), 0600); err != nil {
		certFile.Close()
		keyFile.Close()
		os.Remove(certFile.Name())
		os.Remove(keyFile.Name())
		return "", "", fmt.Errorf("failed to set key file permissions: %w", err)
	}

	if err := pem.Encode(certFile, &pem.Block{Type: "CERTIFICATE", Bytes: certDER}); err != nil {
		certFile.Close()
		keyFile.Close()
		os.Remove(certFile.Name())
		os.Remove(keyFile.Name())
		return "", "", fmt.Errorf("certificate write error: %w", err)
	}

	privateKeyDER, err := x509.MarshalECPrivateKey(privateKey)
	if err != nil {
		certFile.Close()
		keyFile.Close()
		os.Remove(certFile.Name())
		os.Remove(keyFile.Name())
		return "", "", fmt.Errorf("key marshaling error: %w", err)
	}
	if err := pem.Encode(keyFile, &pem.Block{Type: "EC PRIVATE KEY", Bytes: privateKeyDER}); err != nil {
		certFile.Close()
		keyFile.Close()
		os.Remove(certFile.Name())
		os.Remove(keyFile.Name())
		return "", "", fmt.Errorf("key write error: %w", err)
	}

	certPath = certFile.Name()
	keyPath = keyFile.Name()

	if err := certFile.Close(); err != nil {
		logger.Error("Error closing certificate file", "error", err)
	}
	if err := keyFile.Close(); err != nil {
		logger.Error("Error closing key file", "error", err)
	}

	logger.Info("Generated self-signed certificate", "cert", certPath, "key", keyPath)
	return certPath, keyPath, nil
}

// setupPprof sets up pprof routes for profiling
// WARNING: pprof listens ONLY on 127.0.0.1:6060 for security
// Do not expose pprof to the public network without authentication!
// Returns the pprof server for graceful shutdown.
func setupPprof() *http.Server {
	// Create a separate multiplexer for pprof
	pprofMux := http.NewServeMux()
	pprofMux.HandleFunc("/debug/pprof/", pprof.Index)
	pprofMux.HandleFunc("/debug/pprof/cmdline", pprof.Cmdline)
	pprofMux.HandleFunc("/debug/pprof/profile", pprof.Profile)
	pprofMux.HandleFunc("/debug/pprof/symbol", pprof.Symbol)
	pprofMux.HandleFunc("/debug/pprof/trace", pprof.Trace)

	pprofAddr := "127.0.0.1:6060"
	pprofServer := &http.Server{
		Addr:         pprofAddr,
		Handler:      pprofMux,
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	// Start pprof server ONLY on localhost for security
	go func() {
		defer func() {
			if r := recover(); r != nil {
				logger.Error("pprof: goroutine exited with panic", "error", r)
			}
		}()
		logger.Info("pprof server started (localhost only)", "addr", pprofAddr)
		if err := pprofServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			logger.Error("pprof server error", "error", err)
		}
	}()

	return pprofServer
}

// getEnv returns the environment variable value or the default value
func getEnv(key, defaultValue string) string {
	if value, exists := os.LookupEnv(key); exists {
		return value
	}
	return defaultValue
}
