// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/blagovibe/TorrSyncPlayer",
        "contact": {
            "name": "TorrSyncPlayer Support",
            "url": "https://github.com/blagovibe/TorrSyncPlayer/issues",
            "email": "support@torrsyncplayer.local"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/change-password": {
            "post": {
                "description": "Changes the current user's password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Change password",
                "parameters": [
                    {
                        "description": "Password change data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticates the user and returns a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes the JWT token (adds to revoked list)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Registers a new user and returns a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registration",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "description": "Basic server health check (does not require authentication)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/rooms": {
            "post": {
                "description": "Creates a new P2P room for playback synchronization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Create room",
                "parameters": [
                    {
                        "description": "Room data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.CreateRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.RoomInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/rooms/join": {
            "post": {
                "description": "Joins a user to an existing P2P room",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Join room",
                "parameters": [
                    {
                        "description": "Login data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.JoinRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/rooms/leave": {
            "post": {
                "description": "Leaves the current P2P room",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Leave room",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/rooms/signal": {
            "post": {
                "description": "Relays a sync signal (arbitrary JSON payload) to all peers in the room via the server-brokered SSE stream",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Send room sync signal",
                "parameters": [
                    {
                        "description": "Sync signal",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SignalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/rooms/{roomID}/events": {
            "get": {
                "description": "Subscribe to P2P room events in real-time via Server-Sent Events",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Room events (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/sync/pause": {
            "post": {
                "description": "Pauses synchronized playback",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "Pause playback",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SyncStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/sync/play": {
            "post": {
                "description": "Starts synchronized playback",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "Start playback",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SyncStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/sync/seek": {
            "post": {
                "description": "Performs synchronized seek to the specified position",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "Seek",
                "parameters": [
                    {
                        "description": "Seek position",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SeekRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SyncStatus"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sync/status": {
            "get": {
                "description": "Returns the current synchronization status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "Sync status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SyncStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/torrents": {
            "get": {
                "description": "Returns a list of all torrents with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "List torrents",
                "parameters": [
                    {
                        "maximum": 100,
                        "type": "integer",
                        "default": 20,
                        "description": "Record limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.TorrentListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a torrent via magnet link or torrent file and returns its information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Add torrent",
                "parameters": [
                    {
                        "description": "Magnet URI or Torrent File (base64)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.AddTorrentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.TorrentInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/torrents/{id}": {
            "delete": {
                "description": "Removes a torrent by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Remove torrent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/torrents/{id}/buffer/info": {
            "get": {
                "description": "Returns buffer state information for the torrent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Buffer info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.BufferInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/torrents/{id}/buffer/position": {
            "post": {
                "description": "Sets the current playback position for buffer optimization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Set buffer position",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Position in bytes",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SetBufferPositionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/torrents/{id}/files": {
            "get": {
                "description": "Returns a list of torrent files with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "List torrent files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "type": "integer",
                        "default": 20,
                        "description": "Record limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.FileListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/torrents/{id}/select": {
            "post": {
                "description": "Selects a torrent file for streaming by index",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Select file for streaming",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "File index",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SelectFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/torrents/{id}/stream": {
            "get": {
                "description": "Streams the selected torrent file with Range request support",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Stream file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/torrents/{id}/stream-ticket": {
            "post": {
                "description": "Returns a signed ticket authorizing streaming of the given torrent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "torrents"
                ],
                "summary": "Issue stream ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Torrent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.StreamTicketResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.AddTorrentRequest": {
            "type": "object",
            "properties": {
                "magnetUri": {
                    "type": "string"
                },
                "torrentFile": {
                    "description": "base64 encoded torrent file content",
                    "type": "string"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.UserResponse"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.BufferInfo": {
            "type": "object",
            "properties": {
                "buffer_end": {
                    "description": "Buffer end",
                    "type": "integer"
                },
                "buffer_size": {
                    "description": "Buffer size",
                    "type": "integer"
                },
                "buffer_start": {
                    "description": "Buffer start",
                    "type": "integer"
                },
                "buffered_bytes": {
                    "description": "Bytes buffered",
                    "type": "integer"
                },
                "buffered_percent": {
                    "description": "Buffer load percentage",
                    "type": "number"
                },
                "current_position": {
                    "description": "Current position in bytes",
                    "type": "integer"
                },
                "download_speed": {
                    "description": "Download speed (bytes/sec)",
                    "type": "integer"
                },
                "file_index": {
                    "type": "integer"
                },
                "is_buffering": {
                    "description": "Is buffering in progress",
                    "type": "boolean"
                },
                "torrent_id": {
                    "type": "string"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ChangePasswordRequest": {
            "type": "object",
            "properties": {
                "currentPassword": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.CreateRoomRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.FileInfo": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.FileListResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.FileInfo"
                    }
                },
                "hasMore": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.JoinRoomRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "roomId": {
                    "type": "string"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.RegisterRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.RoomInfo": {
            "type": "object",
            "properties": {
                "hostId": {
                    "description": "HostID is the host's peer (session) identifier, NOT the host's user ID.\nThe host's user ID is tracked separately server-side (HostUserID in the\np2p service room struct) and is the authoritative key for host checks.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "peerCount": {
                    "type": "integer"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SeekRequest": {
            "type": "object",
            "properties": {
                "position": {
                    "type": "number"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SelectFileRequest": {
            "type": "object",
            "properties": {
                "fileIndex": {
                    "type": "integer"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SetBufferPositionRequest": {
            "type": "object",
            "properties": {
                "position": {
                    "description": "Position in bytes",
                    "type": "integer"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SignalRequest": {
            "type": "object",
            "properties": {
                "roomId": {
                    "type": "string"
                },
                "signal": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.StreamTicketResponse": {
            "type": "object",
            "properties": {
                "ticket": {
                    "type": "string"
                },
                "torrentId": {
                    "type": "string"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.SyncStatus": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "number"
                },
                "isPlaying": {
                    "type": "boolean"
                },
                "position": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.TorrentInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "progress": {
                    "type": "number"
                },
                "size": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.TorrentListResponse": {
            "type": "object",
            "properties": {
                "hasMore": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "torrents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_blagovibe_TorrSyncPlayer_backend_internal_models.TorrentInfo"
                    }
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        },
        "github_com_blagovibe_TorrSyncPlayer_backend_internal_models.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter JWT token in the format: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8889",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "TorrSyncPlayer API",
	Description:      "HTTP API for TorrSyncPlayer — torrent player with P2P playback synchronization.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
