// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}
