// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo():Promise<Record<string, string>>;

export function Shutdown():Promise<void>;
