// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddICECandidate(arg1, arg2) {
  return window['go']['main']['P2PService']['AddICECandidate'](arg1, arg2);
}

export function BroadcastMessage(arg1) {
  return window['go']['main']['P2PService']['BroadcastMessage'](arg1);
}

export function Close() {
  return window['go']['main']['P2PService']['Close']();
}

export function CreateOffer(arg1) {
  return window['go']['main']['P2PService']['CreateOffer'](arg1);
}

export function CreateRoom() {
  return window['go']['main']['P2PService']['CreateRoom']();
}

export function CreateRoomWithPassword(arg1) {
  return window['go']['main']['P2PService']['CreateRoomWithPassword'](arg1);
}

export function Disconnect() {
  return window['go']['main']['P2PService']['Disconnect']();
}

export function GetLocalPeerID() {
  return window['go']['main']['P2PService']['GetLocalPeerID']();
}

export function GetPeers() {
  return window['go']['main']['P2PService']['GetPeers']();
}

export function GetRoomID() {
  return window['go']['main']['P2PService']['GetRoomID']();
}

export function HandleAnswer(arg1, arg2) {
  return window['go']['main']['P2PService']['HandleAnswer'](arg1, arg2);
}

export function HasRoomPassword() {
  return window['go']['main']['P2PService']['HasRoomPassword']();
}

export function Init(arg1) {
  return window['go']['main']['P2PService']['Init'](arg1);
}

export function IsHost() {
  return window['go']['main']['P2PService']['IsHost']();
}

export function JoinRoom(arg1) {
  return window['go']['main']['P2PService']['JoinRoom'](arg1);
}

export function JoinRoomWithPassword(arg1, arg2) {
  return window['go']['main']['P2PService']['JoinRoomWithPassword'](arg1, arg2);
}

export function JoinRoomWithSDP(arg1, arg2) {
  return window['go']['main']['P2PService']['JoinRoomWithSDP'](arg1, arg2);
}

export function LeaveRoom() {
  return window['go']['main']['P2PService']['LeaveRoom']();
}

export function Pause(arg1) {
  return window['go']['main']['P2PService']['Pause'](arg1);
}

export function Play(arg1) {
  return window['go']['main']['P2PService']['Play'](arg1);
}

export function Seek(arg1) {
  return window['go']['main']['P2PService']['Seek'](arg1);
}

export function SendChatMessage(arg1) {
  return window['go']['main']['P2PService']['SendChatMessage'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['P2PService']['SendMessage'](arg1);
}

export function SendMessageToPeer(arg1, arg2) {
  return window['go']['main']['P2PService']['SendMessageToPeer'](arg1, arg2);
}

export function SendState(arg1) {
  return window['go']['main']['P2PService']['SendState'](arg1);
}

export function SendTorrentInfo(arg1) {
  return window['go']['main']['P2PService']['SendTorrentInfo'](arg1);
}

export function SetRoomPassword(arg1) {
  return window['go']['main']['P2PService']['SetRoomPassword'](arg1);
}

export function VerifyRoomPassword(arg1) {
  return window['go']['main']['P2PService']['VerifyRoomPassword'](arg1);
}
