// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {webrtc} from '../models';
import {main} from '../models';
import {context} from '../models';

export function AddICECandidate(arg1:string,arg2:webrtc.ICECandidateInit):Promise<void>;

export function BroadcastMessage(arg1:main.P2PMessage):Promise<void>;

export function Close():Promise<void>;

export function CreateOffer(arg1:string):Promise<string>;

export function CreateRoom():Promise<string>;

export function CreateRoomWithPassword(arg1:string):Promise<string>;

export function Disconnect():Promise<void>;

export function GetLocalPeerID():Promise<string>;

export function GetPeers():Promise<Array<main.PeerInfo>>;

export function GetRoomID():Promise<string>;

export function HandleAnswer(arg1:string,arg2:string):Promise<void>;

export function HasRoomPassword():Promise<boolean>;

export function Init(arg1:context.Context):Promise<void>;

export function IsHost():Promise<boolean>;

export function JoinRoom(arg1:string):Promise<void>;

export function JoinRoomWithPassword(arg1:string,arg2:string):Promise<void>;

export function JoinRoomWithSDP(arg1:string,arg2:string):Promise<string>;

export function LeaveRoom():Promise<void>;

export function Pause(arg1:number):Promise<void>;

export function Play(arg1:number):Promise<void>;

export function Seek(arg1:number):Promise<void>;

export function SendChatMessage(arg1:string):Promise<void>;

export function SendMessage(arg1:main.P2PMessage):Promise<void>;

export function SendMessageToPeer(arg1:string,arg2:main.P2PMessage):Promise<void>;

export function SendState(arg1:any):Promise<void>;

export function SendTorrentInfo(arg1:any):Promise<void>;

export function SetRoomPassword(arg1:string):Promise<void>;

export function VerifyRoomPassword(arg1:string):Promise<boolean>;
