// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function GetDrift():Promise<number>;

export function GetPlaybackState():Promise<main.PlaybackState>;

export function GetRTT():Promise<number>;

export function GetState():Promise<main.PlaybackState>;

export function GetStats():Promise<main.SyncStats>;

export function GetSyncStats():Promise<main.SyncStats>;

export function HandleSyncCommand(arg1:main.SyncCommand):Promise<void>;

export function Init(arg1:context.Context):Promise<void>;

export function IsHost():Promise<boolean>;

export function OnStateChange(arg1:any):Promise<void>;

export function OnSyncStats(arg1:any):Promise<void>;

export function Pause():Promise<void>;

export function PauseAt(arg1:number):Promise<void>;

export function Play(arg1:number):Promise<void>;

export function Seek(arg1:number):Promise<void>;

export function SetAsGuest():Promise<void>;

export function SetAsHost():Promise<void>;

export function SetLatencyCompensation(arg1:number):Promise<void>;

export function SetP2PService(arg1:main.P2PServiceInterface):Promise<void>;

export function SetPlaybackRate(arg1:number):Promise<void>;

export function SetSyncTolerance(arg1:number):Promise<void>;

export function StartHeartbeat():Promise<void>;

export function SyncNow():Promise<void>;

export function UpdateState(arg1:main.PlaybackState):Promise<void>;
