// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['SyncService']['Close']();
}

export function GetDrift() {
  return window['go']['main']['SyncService']['GetDrift']();
}

export function GetPlaybackState() {
  return window['go']['main']['SyncService']['GetPlaybackState']();
}

export function GetRTT() {
  return window['go']['main']['SyncService']['GetRTT']();
}

export function GetState() {
  return window['go']['main']['SyncService']['GetState']();
}

export function GetStats() {
  return window['go']['main']['SyncService']['GetStats']();
}

export function GetSyncStats() {
  return window['go']['main']['SyncService']['GetSyncStats']();
}

export function HandleSyncCommand(arg1) {
  return window['go']['main']['SyncService']['HandleSyncCommand'](arg1);
}

export function Init(arg1) {
  return window['go']['main']['SyncService']['Init'](arg1);
}

export function IsHost() {
  return window['go']['main']['SyncService']['IsHost']();
}

export function OnStateChange(arg1) {
  return window['go']['main']['SyncService']['OnStateChange'](arg1);
}

export function OnSyncStats(arg1) {
  return window['go']['main']['SyncService']['OnSyncStats'](arg1);
}

export function Pause() {
  return window['go']['main']['SyncService']['Pause']();
}

export function PauseAt(arg1) {
  return window['go']['main']['SyncService']['PauseAt'](arg1);
}

export function Play(arg1) {
  return window['go']['main']['SyncService']['Play'](arg1);
}

export function Seek(arg1) {
  return window['go']['main']['SyncService']['Seek'](arg1);
}

export function SetAsGuest() {
  return window['go']['main']['SyncService']['SetAsGuest']();
}

export function SetAsHost() {
  return window['go']['main']['SyncService']['SetAsHost']();
}

export function SetLatencyCompensation(arg1) {
  return window['go']['main']['SyncService']['SetLatencyCompensation'](arg1);
}

export function SetP2PService(arg1) {
  return window['go']['main']['SyncService']['SetP2PService'](arg1);
}

export function SetPlaybackRate(arg1) {
  return window['go']['main']['SyncService']['SetPlaybackRate'](arg1);
}

export function SetSyncTolerance(arg1) {
  return window['go']['main']['SyncService']['SetSyncTolerance'](arg1);
}

export function StartHeartbeat() {
  return window['go']['main']['SyncService']['StartHeartbeat']();
}

export function SyncNow() {
  return window['go']['main']['SyncService']['SyncNow']();
}

export function UpdateState(arg1) {
  return window['go']['main']['SyncService']['UpdateState'](arg1);
}
