// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrentByFile(arg1) {
  return window['go']['main']['TorrentService']['AddTorrentByFile'](arg1);
}

export function AddTorrentByMagnet(arg1) {
  return window['go']['main']['TorrentService']['AddTorrentByMagnet'](arg1);
}

export function Close() {
  return window['go']['main']['TorrentService']['Close']();
}

export function GetAllTorrents() {
  return window['go']['main']['TorrentService']['GetAllTorrents']();
}

export function GetFile(arg1, arg2) {
  return window['go']['main']['TorrentService']['GetFile'](arg1, arg2);
}

export function GetFiles(arg1) {
  return window['go']['main']['TorrentService']['GetFiles'](arg1);
}

export function GetStreamURL(arg1, arg2) {
  return window['go']['main']['TorrentService']['GetStreamURL'](arg1, arg2);
}

export function GetTorrentInfo(arg1) {
  return window['go']['main']['TorrentService']['GetTorrentInfo'](arg1);
}

export function Init(arg1) {
  return window['go']['main']['TorrentService']['Init'](arg1);
}

export function PauseTorrent(arg1) {
  return window['go']['main']['TorrentService']['PauseTorrent'](arg1);
}

export function RemoveTorrent(arg1) {
  return window['go']['main']['TorrentService']['RemoveTorrent'](arg1);
}

export function ResumeTorrent(arg1) {
  return window['go']['main']['TorrentService']['ResumeTorrent'](arg1);
}

export function SetFilePriority(arg1, arg2, arg3) {
  return window['go']['main']['TorrentService']['SetFilePriority'](arg1, arg2, arg3);
}

export function SetStreamPort(arg1) {
  return window['go']['main']['TorrentService']['SetStreamPort'](arg1);
}

export function StartHTTPServer() {
  return window['go']['main']['TorrentService']['StartHTTPServer']();
}

export function StopHTTPServer() {
  return window['go']['main']['TorrentService']['StopHTTPServer']();
}
