// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddTorrentByFile(arg1:string):Promise<main.TorrentInfo>;

export function AddTorrentByMagnet(arg1:string):Promise<main.TorrentInfo>;

export function Close():Promise<void>;

export function GetAllTorrents():Promise<Array<main.TorrentInfo>>;

export function GetFile(arg1:string,arg2:string):Promise<main.TorrentFile>;

export function GetFiles(arg1:string):Promise<Array<main.TorrentFile>>;

export function GetStreamURL(arg1:string,arg2:string):Promise<string>;

export function GetTorrentInfo(arg1:string):Promise<main.TorrentInfo>;

export function Init(arg1:context.Context):Promise<void>;

export function PauseTorrent(arg1:string):Promise<void>;

export function RemoveTorrent(arg1:string):Promise<void>;

export function ResumeTorrent(arg1:string):Promise<void>;

export function SetFilePriority(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetStreamPort(arg1:number):Promise<void>;

export function StartHTTPServer():Promise<void>;

export function StopHTTPServer():Promise<void>;
